### ISSUE TITLE
404

### ISSUE THREAD

**Issue by Darksonn** [KrishnaSannasi/KrishnaSannasi.github.io#3]
I'm getting a 404 for [your closures post][1].

[1]: https://krishnasannasi.github.io/rust/syntactic/sugar/2019/01/17/Closures-Magic-Functions.html

**Comment by RustyYato** [comment]
Yes, sorry I recently renamed my github account, the new link is

https://rustyyato.github.io/rust/syntactic/sugar/2019/01/17/Closures-Magic-Functions.html
